"""Regenerate assets/maps/{city}-focus.js: every approved area (not just the drawn groups) as path data in the same frames as the SVGs."""
import json, sys
from shapely.geometry import shape
from shapely.ops import transform
def run(repo):
    REPO=repo.rstrip("/")+"/"
    NAMES={'london':{'Mayfair':('mayfair','メイフェア','west-end',True),"St James's":('st-jamess','セント・ジェームズ','west-end',True),'Marylebone':('marylebone','マリルボーン','west-end',True),'Fitzrovia':('fitzrovia','フィッツロヴィア','west-end',True),'Soho':('soho','ソーホー','west-end',True),'Covent Garden':('covent-garden','コヴェント・ガーデン','west-end',True),
      'Holborn / Midtown':('holborn','ホルボーン','midtown',False),'Bloomsbury':('bloomsbury','ブルームズベリー','bloomsbury',False),'City of London':('city','シティ・オブ・ロンドン','city',False),'Westminster':('westminster','ウェストミンスター','westminster',False),'Kensington & Chelsea':('kensington-chelsea','ケンジントン・チェルシー','kc',False)},
     'amsterdam':{'Canal Belt (Grachtengordel)':('canal-belt','カナルベルト（Grachtengordel）','canal',True),'Jordaan':('jordaan','ヨルダーン','jordaan',True),'Oud-Zuid':('oud-zuid','アウド・ザウト','oud-zuid',True),'Zuidas':('zuidas','ザイダス','zuidas',True),
      'Oud-West':('oud-west','アウド・ウェスト','oud-west',False),'Plantage':('plantage','ウェースペルブールト／プランタージュ','plantage',False),'De Pijp':('de-pijp','デ・パイプ','de-pijp',False),'Oost':('oost','オースト','oost',False),'Rivierenbuurt':('rivierenbuurt','リヴィエレンブールト','rivieren',False)}}
    for city in ['london','amsterdam']:
        r=json.load(open(f'out/{city}.json')); out={}
        for variant in ('wide','tall'):
            x0,y0,x1,y1=r['frames'][variant]['bbox']; s=1000.0/(x1-x0)
            T=lambda g: transform(lambda x,y,z=None:((x-x0)*s,(y1-y)*s),g)
            for name,v in r['members'].items():
                g=T(shape(v['geom'])); ps=[g] if g.geom_type=='Polygon' else list(g.geoms)
                d=''.join('M'+'L'.join(f'{x:.0f} {y:.0f}' for x,y in p.exterior.coords)+'Z'+''.join('M'+'L'.join(f'{x:.0f} {y:.0f}' for x,y in i.coords)+'Z' for i in p.interiors) for p in ps)
                out.setdefault(name,{})[variant]=d
        items=[]
        for name,(i,ja,grp,core) in NAMES[city].items(): items.append({'id':i,'name':{'Plantage':'Weesperbuurt/Plantage'}.get(name,name),'ja':ja,'group':grp,'core':core,'wide':out[name]['wide'],'tall':out[name]['tall']})
        vb={v:r['frames'][v]['viewBox'] for v in ('wide','tall')}
        open(REPO+f'assets/maps/{city}-focus.js','w',encoding='utf-8').write(
         f'export const VIEWBOX = {{ wide: "{vb["wide"]}", tall: "{vb["tall"]}" }};\n// Every approved area as path data, in the same frames and projection as {city}-wide.svg and {city}-tall.svg (generated by tools/maps/build.py).\n// Areas sharing a group are drawn as one shape on the page. "core" is the classification: true = core focus, false = selective focus.\nexport const SUBMARKETS = {json.dumps(items,ensure_ascii=False,separators=(",",":"))};\n')
        print(city,len(items))
